[paths]
path_variable_regex = ":(.+?):"
package_root = ""   # leave empty for automatic
user_data = ":package_root:/user_data/"
icons = ":package_root:/resources/icons"
database_schema = ":package_root:/resources/create_tables.sql"
database_file = ":user_data:/user_data.sqlite"
font_path = ":package_root:/resources/Roboto.ttf"

[gui]
initial_viewport_width = 1100
initial_viewport_height = 800

[debug]
manual_render_loop = false